config/routes.rb
Rails.application.routes.draw do
  get 'recruits/new'

  get 'teams/new'

  root 'home#top'
  
  resources :teams, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recruit.rb
class Recruit < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end 

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController
  def new
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/home/top.html.erb
<div class="row mt-3">
  <div class="col">
  </div>
  <div class="col">
  </div>
  <div class="col">
  </div>
  <div class="col">
  </div>
  <div class="col text-center text-white">
    <h1>Sal.com</h1>
  </div>
  <div class="col">
    <button class='btn btn-light'>サイトマップ</button>
  </div>
  <div class="col">
    <%= link_to teams_new_path do %>
      <button class='btn btn-light'>チーム登録</button>
    <% end %>
  </div>
  <div class="col">
    <button class='btn btn-light'>ログイン</button>
  </div>
  <div class="col">
    <button class='btn btn-light'>お問合せ</button>
  </div>
</div>
<div class='container'>
  <div class='text-center'>
    <p class='text-white'>〜シンプルにフットサルしたい人のマッチングサイト〜</p>
  </div>
  <form>
    <div class="row">
      <div class="col">
        <div class="form-group">
          <label for="pref">エリア</label>
          <select class="form-control" id="pref">
            <option value="">都道府県</option>
            <option value="北海道">北海道</option>
            <option value="青森県">青森県</option>
            <option value="宮城県">宮城県</option>
            <option value="岩手県">岩手県</option>
            <option value="秋田県">秋田県</option>
            <option value="山形県">山形県</option>
            <option value="福島県">福島県</option>
            <option value="茨城県">茨城県</option>
            <option value="栃木県">栃木県</option>
            <option value="群馬県">群馬県</option>
            <option value="埼玉県">埼玉県</option>
            <option value="千葉県">千葉県</option>
            <option value="東京都">東京都</option>
            <option value="神奈川県">神奈川県</option>
            <option value="新潟県">新潟県</option>
            <option value="富山県">富山県</option>
            <option value="石川県">石川県</option>
            <option value="福井県">福井県</option>
            <option value="山梨県">山梨県</option>
            <option value="長野県">長野県</option>
            <option value="岐阜県">岐阜県</option>
            <option value="静岡県">静岡県</option>
            <option value="愛知県">愛知県</option>
            <option value="三重県">三重県</option>
            <option value="滋賀県">滋賀県</option>
            <option value="京都府">京都府</option>
            <option value="大阪府">大阪府</option>
            <option value="兵庫県">兵庫県</option>
            <option value="奈良県">奈良県</option>
            <option value="和歌山県">和歌山県</option>
            <option value="鳥取県">鳥取県</option>
            <option value="島根県">島根県</option>
            <option value="岡山県">岡山県</option>
            <option value="広島県">広島県</option>
            <option value="山口県">山口県</option>
            <option value="徳島県">徳島県</option>
            <option value="香川県">香川県</option>
            <option value="愛媛県">愛媛県</option>
            <option value="高知県">高知県</option>
            <option value="福岡県">福岡県</option>
            <option value="佐賀県">佐賀県</option>
            <option value="長崎県">長崎県</option>
            <option value="熊本県">熊本県</option>
            <option value="大分県">大分県</option>
            <option value="宮崎県">宮崎県</option>
            <option value="鹿児島県">鹿児島県</option>
            <option value="沖縄県">沖縄県</option>
          </select>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <label for="teamLevel">チームレベル</label>
          <input type="text" class="form-control" id="teamLevel">
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <label for="date">日時</label>
          <input type="date" class="form-control" id="date">
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <label for="keyword">キーワード</label>
          <input type="text" class="form-control" id="keyword">
        </div>
      </div>
      <div class="col">
        <br>
        <button type="button" class="btn btn-primary mt-1">検索</button>
      </div>
    </div>
  </form>
  
  <h2 class='text-white'>対戦相手募集</h2>
  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">チーム名</th>
        <th scope="col">チームレベル</th>
        <th scope="col">エリア</th>
        <th scope="col">日持</th>
        <th scope="col">紹介文</th>
        <th scope="col">チーム写真</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>バルセロナ</td>
        <td>★★★★★</td>
        <td>東京都品川区</td>
        <td>2020/09/23 19:00 ~ 21:00</td>
        <td>よろしくお願いします！</td>
        <td></td>
      </tr>
      <tr>
        <td>バルセロナ</td>
        <td>★★★★★</td>
        <td>東京都品川区</td>
        <td>2020/09/23 19:00 ~ 21:00</td>
        <td>よろしくお願いします！</td>
        <td></td>
      </tr>
      <tr>
        <td>バルセロナ</td>
        <td>★★★★★</td>
        <td>東京都品川区</td>
        <td>2020/09/23 19:00 ~ 21:00</td>
        <td>よろしくお願いします！</td>
        <td></td>
      </tr>
    </tbody>
  </table> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalCom</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/recruits/new.html.erb
<h1>Recruits#new</h1>
<p>Find me in app/views/recruits/new.html.erb</p>